@baseUrl = http://localhost:5000

GET {{baseUrl}}/api/health

###
GET {{baseUrl}}/api/authors

###
GET {{baseUrl}}/api/books

###
POST {{baseUrl}}/api/authors
Content-Type: application/json

{
  "name": "Pushkin"
}

###
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "title": "Eugene Onegin",
  "authorId": 1
}
