<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Локально: если нет ASP.NET 6 runtime, используем установленный 8.x -->
    <RollForward>Major</RollForward>
  </PropertyGroup>

</Project>
